import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import project1 from '../../../public/images/projects/crypto-screener-cover-image.jpg'
import { FeatureProject, Project } from '@/components/Projects'

export const metadata = {
  title: 'Projects',
  description: 'Generated by create next app'
}

export default function Projects() {
  return (
    <main className='w-full mb-16 flex flex-col items-center justify-center dark:text-light'>
      <Layout className='pt-16'>
        <AnimatedText className='mb-16'>Imagination Trumps Knowledge!</AnimatedText>
        <div className='grid grid-cols-12 gap-24 gap-y-32'>
          <div className='col-span-12'>
            <FeatureProject
              type='Featured Project'
              title='Crypto Screener Application'
              summary='A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency.'
              img={project1}
              link='/'
              github='https://github.com/ilonavarro'
              priority='true'
            />
          </div>
          <div className='col-span-6'>
            <Project
              type='Website Design'
              title='Crypto Screener Application'
              summary='A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency.'
              img={project1}
              link='/'
              github='https://github.com/ilonavarro'
              priority='true'
            />
          </div>

          <div className='col-span-6'>
            <Project
              type='Website Design'
              title='Crypto Screener Application'
              summary='A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency.'
              img={project1}
              link='/'
              github='https://github.com/ilonavarro'
              priority='true'
            />
          </div>

          <div className='col-span-12'>
            <FeatureProject
              type='Featured Project'
              title='Crypto Screener Application'
              summary='A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency.'
              img={project1}
              link='/'
              github='https://github.com/ilonavarro'
            />
          </div>

          <div className='col-span-6'>
            <Project
              type='Website Design'
              title='Crypto Screener Application'
              summary='A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency.'
              img={project1}
              link='/'
              github='https://github.com/ilonavarro'
            />
          </div>

          <div className='col-span-6'>
            <Project
              type='Website Design'
              title='Crypto Screener Application'
              //               summary='A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts.
              // It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your
              // local currency.'
              img={project1}
              link='/'
              github='https://github.com/ilonavarro'
            />
          </div>
        </div>
      </Layout>
    </main>
  )
}
