import AnimatedText from '@/components/AnimatedText'
import Form from '@/components/Form'
import Layout from '@/components/Layout'

export const metadata = {
  title: 'Contact',
  description: 'Generated by create next app'
}

export default function Contact() {
  return (
    <main className='flex w-full flex-col items-center justify-center'>
      <Layout className='pt-16'>
        <AnimatedText className='mb-16'>Keep in touch!</AnimatedText>
        <div className='flex flex-col items-center'>
          <Form />
        </div>
      </Layout>
    </main>
  )
}

//332
