import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import { FeaturedArticle, Article } from '@/components/FeaturedArticle'
import article1 from '../../../public/images/projects/crypto-screener-cover-image.jpg'

export const metadata = {
  title: 'Articles',
  description: 'Generated by create next app'
}

export default function Articles() {
  return (
    <main
      className='w-full mb-16 flex flex-col items-center justify-center overflow-hidden
    dark:text-light'
    >
      <Layout className='pt-16'>
        <AnimatedText className='mb-16'>Words Can Change The World!</AnimatedText>
        <ul className='grid grid-cols-2 gap-16'>
          <FeaturedArticle
            img={article1}
            title='Iniciando na programação: Configurando o computador (WSL)'
            summary='Learn how to build a custom pagination component in ReactJS from scratch. 
Follow this step-by-step guide to integrate Pagination component in your ReactJS project.'
            time='9 min read'
            link='/'
            priority={true}
          />
          <FeaturedArticle
            img={article1}
            title='Build A Custom Pagination Component In Reactjs From Scratch'
            summary='Learn how to build a custom pagination component in ReactJS from scratch. 
Follow this step-by-step guide to integrate Pagination component in your ReactJS project.'
            time='9 min read'
            link='/'
            priority={true}
          />
        </ul>
        <h2 className='font-bold text-4xl w-full text-center mb-16 mt-32'>
          All Articles
        </h2>
        <ul>
          <Article
            title='Iniciando na programação: Configurando o computador (WSL)'
            date='12/08/2022'
            link='/'
            img={article1}
          />
          <Article
            title='Iniciando na programação: Configurando o computador (WSL) 1'
            date='12/08/2022'
            link='/'
            img={article1}
          />
          <Article
            title='Iniciando na programação: Configurando o computador (WSL) 2'
            date='12/08/2022'
            link='/'
            img={article1}
          />
          <Article
            title='Iniciando na programação: Configurando o computador (WSL) 3'
            date='12/08/2022'
            link='/'
            img={article1}
          />
          <Article
            title='Iniciando na programação: Configurando o computador (WSL) 4'
            date='12/08/2022'
            link='/'
            img={article1}
          />
          <Article
            title='Iniciando na programação: Configurando o computador (WSL) 5'
            date='12/08/2022'
            link='/'
            img={article1}
          />
          <Article
            title='Iniciando na programação: Configurando o computador (WSL) 6'
            date='12/08/2022'
            link='/'
            img={article1}
          />
        </ul>
      </Layout>
    </main>
  )
}
